title: Hello, I'm Oren Bochman Data Science Blog.
description: > # this means to ignore newlines until "baseurl:"
  Deep learning, AI, Machine Learning, Bayesian Methods, and more
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://orenbochman.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
site-twitter: #if your site has a twitter account, enter it here
# Author Settings
author: Oren Bochman # add your name
author-img: oren-bochman.png # add your photo
about-author: I am a data scientist focusing on deep learning. # add description
social-twitter:  orenbochman # add your Twitter handle
social-facebook: orenbochman # add your Facebook handle
social-github:   orenbochman # add your Github handle
social-linkedin: orenbochman # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: #orenbochman # add your discus identifier

# Tracker
analytics: UA-90766411-1

# Build Settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true
    semantics: true
    texhints: true

  syntax_highlighter: rouge
#theme: flexible-jekyll
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
paginate: 8
paginate_path: "/page/:num"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      use_math: true
      author: "Oren Bochman"
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "vendor"]